import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Feed from "@/components/Feed";
import { getSession, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Modal from "@/components/Modal";

const inter = Inter({ subsets: ["latin"] });

export default function Home({sessio : session}) {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Modal key = {3} data ={session}  />
      <Header key = "1" data =  { session} />
      <Feed key = "2" data =  { session} />
    </>
  );
}

export async function getServerSideProps(context) {
  const sessio = await getSession(context);
  if (!sessio) {
    return { 
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { sessio },
  };
}